### ISSUE TITLE
[Feature] News storage folder

### ISSUE THREAD

**Issue by johannessteu** [Flow-Community/Community.News#12]
Hey!

What do you think about something like a folder nodetype to store all the news in? Just like a sys-folder in typo3 cms. I'm working on a new project with with > 2000 News. I think it might be easier to sort your news in the tree with different folders. For example for years/months or something like that. Those folders shouldn't be respected in a menue and of course not in the url. For the news list node type there could also be an option to select a folder to show all nodes of that folder. In general it would be possible to use the categories to sort your news, but that might be not really handy if you want to nest it in several levels and most of the news got multiple categories so its always not so easy to decide below wich category all news should be grouped. 

So a tree might look like this:
- [Page] News 
  -- [Community.News:Category] Foo
  -- [Community.News:Category] Bar
  -- [Community.News:Folder] 2015
  ---- [Community.News:Folder] December
  ---- [Community.News:Folder] October

This way you would also decrease the load time for the pagetree if you split your news in several folders. If you sub > 2000 nodes below one node it might take a while to get the tree loaded. Especially if your news are subbed in the first levels

So what do you think? Do you feel good with such a feature? I could start on this

**Comment by sbruggmann** [comment]
Hi Johannes,

A core feature like "Smart Group Node" would be great and this would be a big plus for all.
Something like that is: https://jira.neos.io/browse/NEOS-928
But this task has only 3 votes now.

Stefan
