### ISSUE TITLE
[Feature] Configure NewsList per node

### ISSUE THREAD

**Issue by johannessteu** [Flow-Community/Community.News#13]
As an editor i'd like to configure each newsList-node to override the default settings from Settings.yaml. For Example if you'd like to have just a short newsList without pagination and just with news for a specific category but on another site you'd like to habe a bigger list of news with pagination, more items per page and so on.

Do you feel good with this feature? I'd start with an implementation

**Comment by Weissheiten** [comment]
Thank you for your Input - I feel this is a good feature, but as Community.News was designed to show a very basic example that should provide an approach on how ones own News plugin can be done I'd rather not put this in the main plugin. It WOULD be a great tutorial however if you could post a short reply here with your own news extension when it's done for people who'd like to see how this feature could work.

**Comment by johannessteu** [comment]
Hey @Weissheiten ,
i started my own implementation for a news package here https://github.com/johannessteu/JohannesSteu.Neos.News . Right now it's a really rough implementation. I didn't tagged any version yet. I plan for a v0.1 in the next 2-3 weeks

**Comment by dimaip** [comment]
I like that it's based on `flowpack/listable`, it was just our idea to build simple News example on top of that.
